In [8]:
%pip install psycopg2-binary sqlalchemy pandas matplotlib seaborn

Requirement already satisfied: psycopg2-binary in c:\users\hadi\appdata\local\programs\python\python311\lib\site-packages (2.9.12)
Requirement already satisfied: sqlalchemy in c:\users\hadi\appdata\local\programs\python\python311\lib\site-packages (2.0.51)
Requirement already satisfied: pandas in c:\users\hadi\appdata\local\programs\python\python311\lib\site-packages (3.0.5)
Requirement already satisfied: matplotlib in c:\users\hadi\appdata\local\programs\python\python311\lib\site-packages (3.11.1)
Requirement already satisfied: seaborn in c:\users\hadi\appdata\local\programs\python\python311\lib\site-packages (0.13.2)
Requirement already satisfied: greenlet>=1 in c:\users\hadi\appdata\local\programs\python\python311\lib\site-packages (from sqlalchemy) (3.5.4)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\hadi\appdata\roaming\python\python311\site-packages (from sqlalchemy) (4.16.0)
Requirement already satisfied: numpy>=1.26.0 in c:\users\hadi\appdata\local\programs\python\python311\lib\site-packages (from pandas) (2.4.6)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\hadi\appdata\roaming\python\python311\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\users\hadi\appdata\local\programs\python\python311\lib\site-packages (from pandas) (2026.3)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\hadi\appdata\local\programs\python\python311\lib\site-packages (from matplotlib) (1.3.3)
Requirement already satisfied: cycler>=0.10 in c:\users\hadi\appdata\local\programs\python\python311\lib\site-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.28.2 in c:\users\hadi\appdata\local\programs\python\python311\lib\site-packages (from matplotlib) (4.63.0)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\hadi\appdata\local\programs\python\python311\lib\site-packages (from matplotlib) (1.5.0)
Requirement already satisfied: packaging>=20.0 in c:\users\hadi\appdata\roaming\python\python311\site-packages (from matplotlib) (26.2)
Requirement already satisfied: pillow>=9 in c:\users\hadi\appdata\local\programs\python\python311\lib\site-packages (from matplotlib) (12.3.0)
Requirement already satisfied: pyparsing>=3 in c:\users\hadi\appdata\local\programs\python\python311\lib\site-packages (from matplotlib) (3.3.2)
Requirement already satisfied: six>=1.5 in c:\users\hadi\appdata\roaming\python\python311\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 23.2.1 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [2]:
import pandas as pd
from sqlalchemy import create_engine


DB_USER = "postgres"  
DB_PASSWORD = "eduspark"  
DB_HOST = "localhost"
DB_PORT = "5432"
DB_NAME = "BrizelOliset_db" 


engine = create_engine(
    f"postgresql://{DB_USER}:{DB_PASSWORD}@{DB_HOST}:{DB_PORT}/{DB_NAME}"
)

print("تم الاتصال بنجاح بقاعدة البيانات!")

تم الاتصال بنجاح بقاعدة البيانات!

In [ ]:

query_join = """
SELECT 
    o.order_id,
    o.order_status,
    o.order_purchase_timestamp,
    o.order_estimated_delivery_date,
    c.customer_city,
    c.customer_state
FROM olist_orders_dataset o
JOIN olist_customers_dataset c ON o.customer_id = c.customer_id
LIMIT 10;
"""


df_orders = pd.read_sql(query_join, con=engine)
df_orders

,order_id,order_status,order_purchase_timestamp,order_estimated_delivery_date,customer_city,customer_state
0,e481f51cbdc54678b7cc49136f2d6af7,delivered,2017-10-02 10:56:33,2017-10-18,sao paulo,SP
1,53cdb2fc8bc7dce0b6741e2150273451,delivered,2018-07-24 20:41:37,2018-08-13,barreiras,BA
2,47770eb9100c2d0c44946d9cf07ec65d,delivered,2018-08-08 08:38:49,2018-09-04,vianopolis,GO
3,949d5b44dbf5de918fe9c16f97b45f8a,delivered,2017-11-18 19:28:06,2017-12-15,sao goncalo do amarante,RN
4,ad21c59c0840e6cb83a9ceb5573f8159,delivered,2018-02-13 21:18:39,2018-02-26,santo andre,SP
5,a4591c265e18cb1dcee52889e2d8acc3,delivered,2017-07-09 21:57:05,2017-08-01,congonhinhas,PR
6,136cce7faa42fdb2cefd53fdc79a6098,invoiced,2017-04-11 12:22:08,2017-05-09,santa rosa,RS
7,6514b8ad8028c9f2cc2374ded245783f,delivered,2017-05-16 13:10:30,2017-06-07,nilopolis,RJ
8,76c6e866289321a7c93b82b54852dc33,delivered,2017-01-23 18:29:09,2017-03-06,faxinalzinho,RS
9,e69bfb5eb88e0ed6a785585b27e16dbf,delivered,2017-07-29 11:55:02,2017-08-23,sorocaba,SP

In [5]:
query_target = """
SELECT 
    CASE 
        WHEN order_delivered_customer_date > order_estimated_delivery_date THEN 'Late'
        ELSE 'On Time'
    END AS delivery_status,
    COUNT(*) AS total_orders
FROM olist_orders_dataset
WHERE order_status = 'delivered'
  AND order_delivered_customer_date IS NOT NULL
GROUP BY delivery_status;
"""

df_target = pd.read_sql(query_target, con=engine)
df_target

  delivery_status  total_orders
0         On Time         88644
1            Late          7826